### ISSUE TITLE
Feature request: load multiple libraries

### ISSUE THREAD

**Issue by DanielRuf** [h5p/h5p-cli#21]
It would make sense to have multiple contents to test and also load multiple libraries.

So far only one can be used as `mainLibraryDir`.

**Comment by ralokt** [comment]
This would be really useful.

I'm currently working on a library that processes xAPI events generated by other instances, and my current workaround - create a third runnable "library" that does nothing but load it and another library that generates the events - is just a huge hassle, and not even something that could be distributed/reused properly because it needs to specify the libraries it wants to run as dependencies.

(Side note: if there's a better way that I'm missing here, I'd appreciate to know).

**Comment by ralokt** [comment]
@DanielRuf Why did you close this issue? It's definitely current and still a worthwhile addition...
